config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :subs, only: [:new]
  end
  resource :session

  resources :subs, except: [:new]

  resources :posts do
    resources :comments, only: [:new]
    post "upvote", on: :member
    post "downvote", on: :member
  end

  resources :comments, only: [:create, :show] do
    post "upvote", on: :member
    post "downvote", on: :member
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post

  belongs_to :parent,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :votes, as: :votable

  def vote_score
    score = 0
    self.votes.each{|v| score += v.value}
    score
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in, only: [:new, :create, :edit, :update]

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to @comment.post
    else
      flash[:errors] = @comment.errors.full_messages
      @post = Post.find(comment_params[:post_id])
      redirect_to @post
    end
  end

  def upvote
    @vote = Vote.new(user_id: current_user.id,
                     value: 1,
                     votable_id: params[:id],
                     votable_type: "Comment")
    @vote.save
    flash[:errors] = @vote.errors.full_messages unless @vote.save
    redirect_to :back
  end

  def downvote
    @vote = Vote.new(user_id: current_user.id,
                     value: -1,
                     votable_id: params[:id],
                     votable_type: "Comment")
    @vote.save
    flash[:errors] = @vote.errors.full_messages unless @vote.save
    redirect_to :back
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li> <%= comment.author.username %><%= nice_time(comment.created_at) %>:
  <%= link_to(comment.content, comment_url(comment)) %>
  (<%= comment.vote_score %>)
  <%= button_to("Upvote", upvote_comment_url(comment)) %>
  <%= button_to("Downvote", downvote_comment_url(comment)) %>
</li>
<ul>
  <% @all_comments[comment.id].sort{ |a, b| b.vote_score <=> a.vote_score}.reverse.each do |c2| %>
      <%= render c2 %>
  <% end %>
</ul>

app/views/comments/show.html.erb
<h1>Show Comment</h1>

<h4>Desctiption: </h4>
<ul>
  <li><%= @comment.content %></li>
  <li>  <%= button_to("Upvote", upvote_comment_url(@comment)) %>
    <%= button_to("Downvote", downvote_comment_url(@comment)) %></li>
    <li>Comment score: <%= @comment.vote_score %> </li>
</ul>

<form action="<%= comments_url %>" method="post">
  <%= form_token %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post.id %>">
  <textarea name="comment[content]" rows="4" cols="80"></textarea>
  <br>
  <input type="submit" value="Submit reply">
</form>