config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :subs, only: [:new]
  end
  resource :session

  resources :subs, except: [:new]

  resources :posts do
    resources :comments, only: [:new]
    post "upvote", on: :member
    post "downvote", on: :member
  end

  resources :comments, only: [:create, :show] do
    post "upvote", on: :member
    post "downvote", on: :member
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 4, allow_nil: true }
  validates :session_token, uniqueness: true
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub,
    inverse_of: :moderator

  has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post,
    inverse_of: :author

  has_many :comments,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Comment

  def self.generate_session_token
    SecureRandom::urlsafe_base64(32)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def has_correct_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil unless @user
    return @user if @user.has_correct_password?(password)
    nil
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update

  end

  def edit

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%= users_url %>" method="POST">
  <%= form_token %>
  <label>Username:
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<h1>User Page: <%= @user.username %></h1>
<% if @user.subs.length > 0 %>
  <h4>Moderated Subs</h4>
    <ul>
      <%= render @user.subs %>
    </ul>
<% end %>

<%= button_to("Create a New Sub", new_user_sub_url(current_user), method: :get) %>