config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :subs, only: [:new]
  end
  resource :session

  resources :subs, except: [:new]

  resources :posts do
    resources :comments, only: [:new]
    post "upvote", on: :member
    post "downvote", on: :member
  end

  resources :comments, only: [:create, :show] do
    post "upvote", on: :member
    post "downvote", on: :member
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs, source: :post

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :find_sub, only: [:edit, :update, :show, :destroy]
  before_action :require_logged_in, only: [:new, :create, :edit, :update]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @sub.update(sub_params)
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end


  def show
  end

  def index
    @subs = Sub.all
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator)
  end

  def find_sub
    @sub = Sub.find(params[:id])
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<form action="<%= action  %>" method="post">
  <%= form_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label>Sub Title:
    <input type="text"
           name="sub[title]"
           value="<%= sub.title %>">
  </label>
  <br>
  <label>Description:
    <br>
    <textarea name="sub[description]" rows="8" cols="80">
      <%= sub.description %>
    </textarea>
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/subs/_sub.html.erb
<li><%= link_to(sub.title, sub_url(sub)) %></li>

app/views/subs/edit.html.erb
<h1>Edit Sub: <%= @sub.title %></h1>
<%= render 'form', action: sub_url(@sub),
                   method: :patch,
                   sub: @sub,
                   button_text: "Submit Changes" %>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <%= render @subs %>
</ul>

app/views/subs/new.html.erb
<h1>Create a New Sub</h1>
<%= render 'form', action: subs_url,
                   method: :post,
                   sub: @sub,
                   button_text: "Create Sub" %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h4>Sub Details:</h4>
<ul>
  <li>Moderator: <%= @sub.moderator.username %></li>
  <li>Description: <%= @sub.description %></li>
</ul>

<h4>posts</h4>
<ul>
  <%= render @sub.posts.sort{ |a, b| b.vote_score <=> a.vote_score}.reverse %>
</ul>

<% if current_user == @sub.moderator %>
  <%= button_to("Edit Sub", edit_sub_url(@sub), method: :get) %>
<% end %>
<br>