config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :subs, only: [:new]
  end
  resource :session

  resources :subs, except: [:new]

  resources :posts do
    resources :comments, only: [:new]
    post "upvote", on: :member
    post "downvote", on: :member
  end

  resources :comments, only: [:create, :show] do
    post "upvote", on: :member
    post "downvote", on: :member
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments
  has_many :votes, as: :votable

  def comments_by_parent_id
    h = Hash.new { |h, k| h[k] = [] }
    self.comments.each do |comment|
      h[comment.parent_comment_id] << comment
    end

    h
  end

  def vote_score
    score = 0
    self.votes.each{|v| score += v.value}
    score
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :show, :update, :destroy, :upvote, :downvote]
  before_action :require_logged_in, only: [:new, :create, :edit, :update]


  def upvote
    @vote = Vote.new(user_id: current_user.id,
                     value: 1,
                     votable_id: params[:id],
                     votable_type: "Post")
    flash[:errors] = @vote.errors.full_messages unless @vote.save
    redirect_to :back
  end

  def downvote
    @vote = Vote.new(user_id: current_user.id,
                     value: -1,
                     votable_id: params[:id],
                     votable_type: "Post")
    @vote.save
    flash[:errors] = @vote.errors.full_messages unless @vote.save
    redirect_to :back
  end

  def show
    @all_comments = @post.comments_by_parent_id
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to @post
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end

  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end


  def destroy
    @post.destroy
    redirect_to subs_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form  action="<%= action %>" method="post">
  <%= form_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label>Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>
  <label>URL:
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label><br>

  <label>Content:
    <br>
    <textarea name="post[content]" rows="8" cols="80">
      <%= post.content %>
    </textarea>
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>

  <br>
  <input type="submit"  value="<%= button_text  %>">


</form>

app/views/posts/_post.html.erb
<li> <%= link_to post.title, post_url(post) %>
  (<%= post.vote_score %>)
  <%= button_to("Upvote", upvote_post_url(post)) %>
  <%= button_to("Downvote", downvote_post_url(post)) %>
</li>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form', action: post_url(@post),
                   method: :patch,
                   button_text: "Edit Post",
                   post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', action: posts_url,
                   method: :post,
                   button_text: "Create Post",
                   post: @post %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>

<h4>Post Description</h4>
<ul>
  <li>Author: <%= @post.author.username %></li>
  <li>Content: <%= @post.content %></li>
  <li>Post Score: <%= @post.vote_score %></li>
  <li><%= button_to("Upvote", upvote_post_url(@post)) %>
  <%= button_to("Downvote", downvote_post_url(@post)) %></li>
</ul>

<% if @post.comments.length > 0 %>
  <h4>Comments: </h4>

  <ul>
    <% @all_comments[nil].sort{ |a, b| b.vote_score <=> a.vote_score}.each do |comment| %>
      <%= render comment %>
    <% end %>
  </ul>
<% end %>

<% if current_user %>
  <h4>New Comment</h4>

  <form  action="<%= comments_url %>" method="post">
    <%= form_token %>
    <label>
      <textarea name="comment[content]" rows="4" cols="80"></textarea>
      <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
    </label>
    <br>
    <input type="submit" value="Create Comment">
  </form>
<% end %>

<% if current_user == @post.author %>
  <%= button_to("Edit Post", edit_post_url(@post), method: :get) %>
  <%= button_to("Delete Post", post_url(@post), method: :delete) %>
<% end %>